// privacy-safe share payload excludes contact, invoice, shipping and notes
(() => {
'use strict';
const VERSION='0.5.0.v1';
const DRAFT_KEY='pgw-production-draft-v98-verified-drawings-and-ux';
const LANG_KEY='pgw-language-v050v1';
const UI_KEY='pgw-accessibility-v050v1';
const SUPPORTED=['pl','en','de','cs','sk','uk'];
const LANG_NAMES={pl:'Polski',en:'English',de:'Deutsch',cs:'Čeština',sk:'Slovenčina',uk:'Українська'};
const SUITE={
 pl:{passport:'Paszport serwisowy',close:'Zamknij',version:'Wersja',caseCode:'Kod sprawy',model:'Model',parts:'Części',privacy:'Link udostępniania zawiera wyłącznie model i wybrane części. Nie zawiera imienia, telefonu, adresu, NIP ani treści uwag.',share:'Udostępnij bez danych osobowych',copyCase:'Kopiuj kod sprawy',print:'Drukuj / zapisz PDF',email:'Wyślij e-mail',clear:'Usuń dane kontaktowe',install:'Zainstaluj aplikację',access:'Tryb dostępności',large:'Duży tekst',contrast:'Wysoki kontrast',motion:'Mniej animacji',safeCopied:'Skopiowano bezpieczny link.',caseCopied:'Skopiowano kod sprawy.',contactsCleared:'Dane kontaktowe usunięte.',sharedLoaded:'Wczytano bezpieczny link zapytania.',online:'Online',offline:'Offline'},
 en:{passport:'Service Passport',close:'Close',version:'Version',caseCode:'Case code',model:'Model',parts:'Parts',privacy:'The share link contains only the device model and selected parts. It never contains your name, phone, address, tax ID or notes.',share:'Share without personal data',copyCase:'Copy case code',print:'Print / save PDF',email:'Send email',clear:'Clear contact details',install:'Install app',access:'Accessibility',large:'Large text',contrast:'High contrast',motion:'Reduced motion',safeCopied:'Safe link copied.',caseCopied:'Case code copied.',contactsCleared:'Contact details cleared.',sharedLoaded:'Shared request loaded.',online:'Online',offline:'Offline'},
 de:{passport:'Service-Pass',close:'Schließen',version:'Version',caseCode:'Fallcode',model:'Modell',parts:'Teile',privacy:'Der Freigabelink enthält nur Gerätemodell und ausgewählte Teile - keine Namen, Telefonnummern, Adressen, Steuerdaten oder Hinweise.',share:'Ohne persönliche Daten teilen',copyCase:'Fallcode kopieren',print:'Drucken / PDF speichern',email:'E-Mail senden',clear:'Kontaktdaten löschen',install:'App installieren',access:'Barrierefreiheit',large:'Große Schrift',contrast:'Hoher Kontrast',motion:'Weniger Animationen',safeCopied:'Sicherer Link kopiert.',caseCopied:'Fallcode kopiert.',contactsCleared:'Kontaktdaten gelöscht.',sharedLoaded:'Geteilte Anfrage geladen.',online:'Online',offline:'Offline'},
 cs:{passport:'Servisní pas',close:'Zavřít',version:'Verze',caseCode:'Kód případu',model:'Model',parts:'Díly',privacy:'Sdílený odkaz obsahuje pouze model zařízení a vybrané díly. Neobsahuje jméno, telefon, adresu, daňové údaje ani poznámky.',share:'Sdílet bez osobních údajů',copyCase:'Kopírovat kód případu',print:'Tisk / uložit PDF',email:'Odeslat e-mail',clear:'Smazat kontaktní údaje',install:'Nainstalovat aplikaci',access:'Přístupnost',large:'Velký text',contrast:'Vysoký kontrast',motion:'Méně animací',safeCopied:'Bezpečný odkaz zkopírován.',caseCopied:'Kód případu zkopírován.',contactsCleared:'Kontaktní údaje smazány.',sharedLoaded:'Sdílená poptávka načtena.',online:'Online',offline:'Offline'},
 sk:{passport:'Servisný pas',close:'Zavrieť',version:'Verzia',caseCode:'Kód prípadu',model:'Model',parts:'Diely',privacy:'Zdieľaný odkaz obsahuje iba model zariadenia a vybrané diely. Neobsahuje meno, telefón, adresu, daňové údaje ani poznámky.',share:'Zdieľať bez osobných údajov',copyCase:'Kopírovať kód prípadu',print:'Tlačiť / uložiť PDF',email:'Odoslať e-mail',clear:'Vymazať kontaktné údaje',install:'Nainštalovať aplikáciu',access:'Prístupnosť',large:'Veľký text',contrast:'Vysoký kontrast',motion:'Menej animácií',safeCopied:'Bezpečný odkaz skopírovaný.',caseCopied:'Kód prípadu skopírovaný.',contactsCleared:'Kontaktné údaje vymazané.',sharedLoaded:'Zdieľaný dopyt načítaný.',online:'Online',offline:'Offline'},
 uk:{passport:'Сервісний паспорт',close:'Закрити',version:'Версія',caseCode:'Код звернення',model:'Модель',parts:'Запчастини',privacy:'Посилання містить лише модель пристрою та вибрані запчастини. Воно не містить імені, телефону, адреси, податкових даних чи приміток.',share:'Поділитися без персональних даних',copyCase:'Копіювати код звернення',print:'Друк / зберегти PDF',email:'Надіслати e-mail',clear:'Видалити контактні дані',install:'Встановити застосунок',access:'Доступність',large:'Великий текст',contrast:'Високий контраст',motion:'Менше анімації',safeCopied:'Безпечне посилання скопійовано.',caseCopied:'Код звернення скопійовано.',contactsCleared:'Контактні дані видалено.',sharedLoaded:'Спільний запит завантажено.',online:'Онлайн',offline:'Офлайн'}
};

const T={
 en:{'Serwis Pogwarancyjny TOYA':'TOYA After-Warranty Service','Krokowy formularz zapytania o części':'Step-by-step spare parts request','Formularz zapytania o części':'Spare parts request form','Znajdź urządzenie, wybierz część i przygotuj zapytanie do serwisu.':'Find your device, select a part and prepare a service request.','Wyszukaj urządzenie':'Find a device','Wybierz części z listy':'Select parts from the list','Dane kontaktowe, faktura i wysyłka':'Contact, invoice and delivery','Gotowy mail do skopiowania':'Ready-to-copy email','Urządzenie':'Device','Części':'Parts','Dane':'Details','Mail':'Email','Indeks lub nazwa urządzenia':'Device index or name','Marka urządzenia':'Device brand','Wszystkie marki':'All brands','Wybierz':'Select','Dodaj':'Add','Dodano':'Added','Przejdź do danych':'Continue to details','Wróć do wyboru urządzenia':'Back to device selection','Szukaj części w tym urządzeniu':'Search parts for this device','Pokaż więcej części':'Show more parts','Kontakt':'Contact','Faktura':'Invoice','Wysyłka':'Delivery','Dodatkowa wiadomość':'Additional message','Uwagi':'Notes','Przejdź do gotowego maila':'Create final email','Kopiuj treść maila':'Copy email body','Kopiuj temat':'Copy subject','Kopiuj komplet':'Copy all','Popraw dane':'Edit details','Zacznij od nowa':'Start over','Aktualny krok':'Current step','Postęp zapytania':'Request progress','Wybrane części':'Selected parts','Brak wybranych części.':'No selected parts.','Rysunek PDF':'PDF drawing','Lista części':'Parts list','Otwórz w nowej karcie':'Open in new tab','Wyczyść':'Clear','Dalej':'Next','Gotowe':'Ready','Ładowanie formularza…':'Loading form…','Nie udało się załadować danych':'Could not load data','Imię i nazwisko / firma kontaktowa':'Name / contact company','Telefon':'Phone','Numer seryjny urządzenia':'Device serial number','Opis potrzebnej części':'Required part description','Chcę podać dane do faktury teraz':'I want to provide invoice details now','Chcę podać adres wysyłki teraz':'I want to provide delivery address now','Takie same jak do faktury':'Same as invoice','Odbiorca':'Recipient','Ulica i nr':'Street and number','Kod pocztowy':'Postal code','Miasto':'City','Telefon dla kuriera':'Courier phone','Adresat':'Recipient','Temat':'Subject','Treść':'Message','Język':'Language','Paszport serwisowy':'Service Passport','Udostępnij bez danych osobowych':'Share without personal data','Drukuj / zapisz PDF':'Print / save PDF','Wyślij e-mail':'Send email','Usuń dane kontaktowe':'Clear contact details','Kod sprawy':'Case code','Online':'Online','Offline':'Offline','Tryb dostępności':'Accessibility mode','Duży tekst':'Large text','Wysoki kontrast':'High contrast','Mniej animacji':'Reduced motion','Zainstaluj aplikację':'Install app'},
 de:{'Serwis Pogwarancyjny TOYA':'TOYA Service nach der Garantie','Krokowy formularz zapytania o części':'Schrittweise Ersatzteilanfrage','Formularz zapytania o części':'Ersatzteilanfrage','Znajdź urządzenie, wybierz część i przygotuj zapytanie do serwisu.':'Gerät finden, Teil auswählen und Serviceanfrage vorbereiten.','Wyszukaj urządzenie':'Gerät suchen','Wybierz części z listy':'Teile auswählen','Dane kontaktowe, faktura i wysyłka':'Kontakt, Rechnung und Versand','Gotowy mail do skopiowania':'Fertige E-Mail','Urządzenie':'Gerät','Części':'Teile','Dane':'Daten','Mail':'E-Mail','Indeks lub nazwa urządzenia':'Geräteindex oder Name','Marka urządzenia':'Gerätemarke','Wszystkie marki':'Alle Marken','Wybierz':'Auswählen','Dodaj':'Hinzufügen','Dodano':'Hinzugefügt','Przejdź do danych':'Weiter zu den Daten','Wróć do wyboru urządzenia':'Zurück zur Geräteauswahl','Szukaj części w tym urządzeniu':'Teile in diesem Gerät suchen','Pokaż więcej części':'Mehr Teile anzeigen','Kontakt':'Kontakt','Faktura':'Rechnung','Wysyłka':'Versand','Dodatkowa wiadomość':'Zusätzliche Nachricht','Uwagi':'Hinweise','Przejdź do gotowego maila':'E-Mail erstellen','Kopiuj treść maila':'E-Mail-Text kopieren','Kopiuj temat':'Betreff kopieren','Kopiuj komplet':'Alles kopieren','Popraw dane':'Daten bearbeiten','Zacznij od nowa':'Neu beginnen','Aktualny krok':'Aktueller Schritt','Postęp zapytania':'Fortschritt','Wybrane części':'Ausgewählte Teile','Brak wybranych części.':'Keine Teile ausgewählt.','Rysunek PDF':'PDF-Zeichnung','Lista części':'Teileliste','Otwórz w nowej karcie':'In neuem Tab öffnen','Wyczyść':'Leeren','Dalej':'Weiter','Gotowe':'Bereit','Ładowanie formularza…':'Formular wird geladen…','Język':'Sprache','Paszport serwisowy':'Service-Pass','Udostępnij bez danych osobowych':'Ohne persönliche Daten teilen','Drukuj / zapisz PDF':'Drucken / als PDF speichern','Wyślij e-mail':'E-Mail senden','Usuń dane kontaktowe':'Kontaktdaten löschen','Kod sprawy':'Fallcode','Online':'Online','Offline':'Offline','Tryb dostępności':'Barrierefreiheit','Duży tekst':'Große Schrift','Wysoki kontrast':'Hoher Kontrast','Mniej animacji':'Weniger Animationen','Zainstaluj aplikację':'App installieren'},
 cs:{'Serwis Pogwarancyjny TOYA':'Pozáruční servis TOYA','Krokowy formularz zapytania o części':'Průvodce poptávkou náhradních dílů','Formularz zapytania o części':'Poptávka náhradních dílů','Znajdź urządzenie, wybierz część i przygotuj zapytanie do serwisu.':'Najděte zařízení, vyberte díl a připravte servisní poptávku.','Wyszukaj urządzenie':'Vyhledat zařízení','Wybierz części z listy':'Vybrat díly','Dane kontaktowe, faktura i wysyłka':'Kontakt, faktura a doprava','Gotowy mail do skopiowania':'Hotový e-mail','Urządzenie':'Zařízení','Części':'Díly','Dane':'Údaje','Mail':'E-mail','Indeks lub nazwa urządzenia':'Index nebo název zařízení','Marka urządzenia':'Značka zařízení','Wszystkie marki':'Všechny značky','Wybierz':'Vybrat','Dodaj':'Přidat','Dodano':'Přidáno','Przejdź do danych':'Pokračovat k údajům','Wróć do wyboru urządzenia':'Zpět na výběr zařízení','Szukaj części w tym urządzeniu':'Hledat díly v zařízení','Pokaż więcej części':'Zobrazit více dílů','Kontakt':'Kontakt','Faktura':'Faktura','Wysyłka':'Doprava','Dodatkowa wiadomość':'Další zpráva','Uwagi':'Poznámky','Przejdź do gotowego maila':'Vytvořit e-mail','Kopiuj treść maila':'Kopírovat text e-mailu','Kopiuj temat':'Kopírovat předmět','Kopiuj komplet':'Kopírovat vše','Popraw dane':'Upravit údaje','Zacznij od nowa':'Začít znovu','Aktualny krok':'Aktuální krok','Postęp zapytania':'Průběh poptávky','Wybrane części':'Vybrané díly','Brak wybranych części.':'Nejsou vybrány žádné díly.','Rysunek PDF':'PDF výkres','Lista części':'Seznam dílů','Otwórz w nowej karcie':'Otevřít v nové kartě','Wyczyść':'Vymazat','Dalej':'Dále','Gotowe':'Připraveno','Ładowanie formularza…':'Načítání formuláře…','Język':'Jazyk','Paszport serwisowy':'Servisní pas','Udostępnij bez danych osobowych':'Sdílet bez osobních údajů','Drukuj / zapisz PDF':'Tisk / uložit PDF','Wyślij e-mail':'Odeslat e-mail','Usuń dane kontaktowe':'Smazat kontaktní údaje','Kod sprawy':'Kód případu','Online':'Online','Offline':'Offline','Tryb dostępności':'Přístupnost','Duży tekst':'Velký text','Wysoki kontrast':'Vysoký kontrast','Mniej animacji':'Méně animací','Zainstaluj aplikację':'Nainstalovat aplikaci'},
 sk:{'Serwis Pogwarancyjny TOYA':'Pozáručný servis TOYA','Krokowy formularz zapytania o części':'Sprievodca dopytom náhradných dielov','Formularz zapytania o części':'Dopyt náhradných dielov','Znajdź urządzenie, wybierz część i przygotuj zapytanie do serwisu.':'Nájdite zariadenie, vyberte diel a pripravte servisný dopyt.','Wyszukaj urządzenie':'Vyhľadať zariadenie','Wybierz części z listy':'Vybrať diely','Dane kontaktowe, faktura i wysyłka':'Kontakt, faktúra a doprava','Gotowy mail do skopiowania':'Hotový e-mail','Urządzenie':'Zariadenie','Części':'Diely','Dane':'Údaje','Mail':'E-mail','Indeks lub nazwa urządzenia':'Index alebo názov zariadenia','Marka urządzenia':'Značka zariadenia','Wszystkie marki':'Všetky značky','Wybierz':'Vybrať','Dodaj':'Pridať','Dodano':'Pridané','Przejdź do danych':'Pokračovať k údajom','Wróć do wyboru urządzenia':'Späť na výber zariadenia','Szukaj części w tym urządzeniu':'Hľadať diely v zariadení','Pokaż więcej części':'Zobraziť viac dielov','Kontakt':'Kontakt','Faktura':'Faktúra','Wysyłka':'Doprava','Dodatkowa wiadomość':'Ďalšia správa','Uwagi':'Poznámky','Przejdź do gotowego maila':'Vytvoriť e-mail','Kopiuj treść maila':'Kopírovať text e-mailu','Kopiuj temat':'Kopírovať predmet','Kopiuj komplet':'Kopírovať všetko','Popraw dane':'Upraviť údaje','Zacznij od nowa':'Začať znova','Aktualny krok':'Aktuálny krok','Postęp zapytania':'Priebeh dopytu','Wybrane części':'Vybrané diely','Brak wybranych części.':'Nie sú vybrané žiadne diely.','Rysunek PDF':'PDF výkres','Lista części':'Zoznam dielov','Otwórz w nowej karcie':'Otvoriť na novej karte','Wyczyść':'Vymazať','Dalej':'Ďalej','Gotowe':'Pripravené','Ładowanie formularza…':'Načítanie formulára…','Język':'Jazyk','Paszport serwisowy':'Servisný pas','Udostępnij bez danych osobowych':'Zdieľať bez osobných údajov','Drukuj / zapisz PDF':'Tlačiť / uložiť PDF','Wyślij e-mail':'Odoslať e-mail','Usuń dane kontaktowe':'Vymazať kontaktné údaje','Kod sprawy':'Kód prípadu','Online':'Online','Offline':'Offline','Tryb dostępności':'Prístupnosť','Duży tekst':'Veľký text','Wysoki kontrast':'Vysoký kontrast','Mniej animacji':'Menej animácií','Zainstaluj aplikację':'Nainštalovať aplikáciu'},
 uk:{'Serwis Pogwarancyjny TOYA':'Післягарантійний сервіс TOYA','Krokowy formularz zapytania o części':'Покроковий запит на запчастини','Formularz zapytania o części':'Запит на запчастини','Znajdź urządzenie, wybierz część i przygotuj zapytanie do serwisu.':'Знайдіть пристрій, виберіть деталь і підготуйте запит до сервісу.','Wyszukaj urządzenie':'Знайти пристрій','Wybierz części z listy':'Вибрати деталі','Dane kontaktowe, faktura i wysyłka':'Контакт, рахунок і доставка','Gotowy mail do skopiowania':'Готовий лист','Urządzenie':'Пристрій','Części':'Деталі','Dane':'Дані','Mail':'Лист','Indeks lub nazwa urządzenia':'Індекс або назва пристрою','Marka urządzenia':'Бренд пристрою','Wszystkie marki':'Усі бренди','Wybierz':'Вибрати','Dodaj':'Додати','Dodano':'Додано','Przejdź do danych':'Перейти до даних','Wróć do wyboru urządzenia':'Назад до вибору пристрою','Szukaj części w tym urządzeniu':'Шукати деталі для пристрою','Pokaż więcej części':'Показати більше деталей','Kontakt':'Контакт','Faktura':'Рахунок','Wysyłka':'Доставка','Dodatkowa wiadomość':'Додаткове повідомлення','Uwagi':'Примітки','Przejdź do gotowego maila':'Створити лист','Kopiuj treść maila':'Копіювати текст листа','Kopiuj temat':'Копіювати тему','Kopiuj komplet':'Копіювати все','Popraw dane':'Редагувати дані','Zacznij od nowa':'Почати заново','Aktualny krok':'Поточний крок','Postęp zapytania':'Хід запиту','Wybrane części':'Вибрані деталі','Brak wybranych części.':'Деталі не вибрані.','Rysunek PDF':'PDF-креслення','Lista części':'Список деталей','Otwórz w nowej karcie':'Відкрити в новій вкладці','Wyczyść':'Очистити','Dalej':'Далі','Gotowe':'Готово','Ładowanie formularza…':'Завантаження форми…','Język':'Мова','Paszport serwisowy':'Сервісний паспорт','Udostępnij bez danych osobowych':'Поділитися без персональних даних','Drukuj / zapisz PDF':'Друк / зберегти PDF','Wyślij e-mail':'Надіслати лист','Usuń dane kontaktowe':'Видалити контактні дані','Kod sprawy':'Код звернення','Online':'Онлайн','Offline':'Офлайн','Tryb dostępności':'Доступність','Duży tekst':'Великий текст','Wysoki kontrast':'Високий контраст','Mniej animacji':'Менше анімацій','Zainstaluj aplikację':'Встановити застосунок'}
};
const originals=new WeakMap(), attrOriginals=new WeakMap();
let lang='pl', translateQueued=false, installPrompt=null;
function clean(s){return String(s??'').replace(/\s+/g,' ').trim()}
function tr(s){if(lang==='pl'||!s)return s;const lead=s.match(/^\s*/)?.[0]||'',trail=s.match(/\s*$/)?.[0]||'',c=clean(s),d=T[lang]||{};if(d[c])return lead+d[c]+trail;
 const pats=[
  [/^Znaleziono (\d+) pasujących urządzeń(.*)\.$/,lang==='en'?'Found $1 matching devices$2.':lang==='de'?'$1 passende Geräte gefunden$2.':lang==='uk'?'Знайдено $1 відповідних пристроїв$2.':'Nájdené zariadenia: $1$2.'],
  [/^Ten rysunek ma (\d+) części\.(.*)$/,lang==='en'?'This drawing contains $1 parts.$2':lang==='de'?'Diese Zeichnung enthält $1 Teile.$2':lang==='uk'?'Це креслення містить $1 деталей.$2':'Tento výkres obsahuje $1 dielov.$2'],
  [/^Części: (\d+) • urządzeń: (\d+)$/,lang==='en'?'Parts: $1 • devices: $2':lang==='de'?'Teile: $1 • Geräte: $2':lang==='uk'?'Деталі: $1 • пристрої: $2':'Diely: $1 • zariadenia: $2'],
  [/^Pokaż więcej części \((\d+) pozostało\)$/,lang==='en'?'Show more parts ($1 left)':lang==='de'?'Mehr Teile anzeigen ($1 übrig)':lang==='uk'?'Показати більше деталей (залишилось $1)':'Zobraziť viac dielov (zostáva $1)']
 ];
 for(const [r,v] of pats)if(r.test(c))return lead+c.replace(r,v)+trail;return s}
function translateNode(node){if(node.nodeType!==3||!clean(node.nodeValue))return;const p=node.parentElement;if(!p||/^(SCRIPT|STYLE|NOSCRIPT|TEXTAREA|INPUT)$/.test(p.tagName)||p.closest('.no-i18n'))return;if(!originals.has(node))originals.set(node,node.nodeValue);node.nodeValue=tr(originals.get(node));}
function translateAttrs(el){if(!el||!el.getAttribute)return;let saved=attrOriginals.get(el);if(!saved){saved={};for(const a of ['placeholder','title','aria-label'])if(el.hasAttribute(a))saved[a]=el.getAttribute(a);attrOriginals.set(el,saved)}for(const [a,v] of Object.entries(saved))el.setAttribute(a,tr(v));}
function renderSuiteLocale(){const l=SUITE[lang]||SUITE.pl;const text=(id,key)=>{const el=document.getElementById(id);if(el)el.textContent=l[key]};text('pgwPassportLabel','passport');text('pgwPassportTitle','passport');text('pgwVersionLabel','version');text('pgwCaseLabel','caseCode');text('pgwModelLabel','model');text('pgwPartsLabel','parts');text('pgwPrivacy','privacy');text('pgwShareLabel','share');text('pgwCopyCaseLabel','copyCase');text('pgwPrintLabel','print');text('pgwEmailLabel','email');text('pgwClearLabel','clear');text('pgwInstallLabel','install');text('pgwAccessLegend','access');text('pgwLargeLabel','large');text('pgwContrastLabel','contrast');text('pgwMotionLabel','motion');const close=document.getElementById('pgwPassportClose');if(close)close.setAttribute('aria-label',l.close);const select=document.getElementById('pgwLanguage');if(select)select.value=lang;updateNetwork()}
function translateAll(){document.documentElement.lang=lang;document.title=lang==='pl'?'Formularz zapytania o części — Serwis Pogwarancyjny TOYA':lang==='en'?'TOYA Spare Parts Request':lang==='de'?'TOYA Ersatzteilanfrage':lang==='uk'?'Запит запчастин TOYA':'TOYA – náhradné diely';const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);while(w.nextNode())translateNode(w.currentNode);document.querySelectorAll('input,textarea,button,a,select,[title],[aria-label]').forEach(translateAttrs);renderSuiteLocale()}
function queueTranslate(){if(translateQueued)return;translateQueued=true;requestAnimationFrame(()=>{translateQueued=false;translateAll()})}
function setLang(v){lang=SUPPORTED.includes(v)?v:'pl';localStorage.setItem(LANG_KEY,lang);const u=new URL(location.href);u.searchParams.set('lang',lang);history.replaceState(null,'',u);queueTranslate();}
function readDraft(){try{return JSON.parse(localStorage.getItem(DRAFT_KEY)||'{}')}catch{return {}}}
function safePayload(){const d=readDraft();return{v:1,deviceIndex:d.deviceIndex||'',drawingId:d.drawingId||'',parts:Array.isArray(d.parts)?d.parts:[],manualMode:!!d.manualMode,activeBrand:d.activeBrand||'all'}}
function b64e(o){const bytes=new TextEncoder().encode(JSON.stringify(o));let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64d(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
function shareUrl(){const p=safePayload(),u=new URL(location.href);u.searchParams.delete('share');u.hash='pgw='+b64e(p);return u.toString()}
async function copy(v,msg){try{await navigator.clipboard.writeText(v);toast(msg)}catch{prompt(msg,v)}}
function hash(s){let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return(h>>>0).toString(36).toUpperCase().padStart(7,'0')}
function caseCode(){const p=safePayload();return `PGW-${(p.deviceIndex||'MANUAL').replace(/[^A-Z0-9]/gi,'').toUpperCase()}-${hash(JSON.stringify(p)).slice(0,6)}`}
function toast(msg){let t=document.getElementById('pgwToast');if(!t){t=document.createElement('div');t.id='pgwToast';t.className='pgw-toast no-i18n';document.body.append(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2600)}
function clearContacts(){const d=readDraft();if(d.form){for(const k of Object.keys(d.form))d.form[k]=''}d.wantInvoice=false;d.wantShipping=false;d.sameAsInvoice=false;localStorage.setItem(DRAFT_KEY,JSON.stringify(d));document.querySelectorAll('#customerForm input,#customerForm textarea').forEach(el=>{if(el.type==='checkbox')el.checked=false;else el.value=''});document.querySelector('#customerForm')?.dispatchEvent(new Event('input',{bubbles:true}));toast((SUITE[lang]||SUITE.pl).contactsCleared);updateSuite()}
function openMail(){const to=document.getElementById('mailTo')?.value||'service@yato.pl',subject=document.getElementById('mailSubject')?.value||`PGW ${caseCode()}`,body=document.getElementById('mailBody')?.value||'';location.href=`mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
function createSuite(){if(document.getElementById('pgwClientSuite'))return;const top=document.querySelector('.top-actions')||document.querySelector('.topbar')||document.body;const box=document.createElement('div');box.id='pgwClientSuite';box.className='pgw-client-suite no-i18n';box.innerHTML=`<label class="pgw-lang"><span aria-hidden="true">🌐</span><select id="pgwLanguage" aria-label="Język">${SUPPORTED.map(c=>`<option value="${c}">${LANG_NAMES[c]}</option>`).join('')}</select></label><button id="pgwPassportOpen" type="button">🪪 <span id="pgwPassportLabel">Paszport serwisowy</span></button><span id="pgwNet" class="pgw-net" role="status"></span>`;top.append(box);
 const drawer=document.createElement('aside');drawer.id='pgwPassport';drawer.className='pgw-passport no-i18n';drawer.setAttribute('aria-hidden','true');drawer.setAttribute('aria-labelledby','pgwPassportTitle');drawer.innerHTML=`<div class="pgw-passport-head"><div><small>TOYA GLOBAL SERVICE HUB</small><h2 id="pgwPassportTitle">Paszport serwisowy</h2></div><button id="pgwPassportClose" aria-label="Zamknij">×</button></div><div class="pgw-passport-grid"><div><span id="pgwVersionLabel">Wersja</span><b>${VERSION}</b></div><div><span id="pgwCaseLabel">Kod sprawy</span><b id="pgwCase">-</b></div><div><span id="pgwModelLabel">Model</span><b id="pgwModel">-</b></div><div><span id="pgwPartsLabel">Części</span><b id="pgwPartCount">0</b></div></div><p id="pgwPrivacy" class="pgw-privacy">🔒 Link udostępniania zawiera wyłącznie model i wybrane części.</p><div class="pgw-actions"><button id="pgwShare">🔗 <span id="pgwShareLabel">Udostępnij bez danych osobowych</span></button><button id="pgwCopyCase">📋 <span id="pgwCopyCaseLabel">Kopiuj kod sprawy</span></button><button id="pgwPrint">🖨 <span id="pgwPrintLabel">Drukuj / zapisz PDF</span></button><button id="pgwEmail">✉ <span id="pgwEmailLabel">Wyślij e-mail</span></button><button id="pgwClearContacts">🧹 <span id="pgwClearLabel">Usuń dane kontaktowe</span></button><button id="pgwInstall" hidden>⬇ <span id="pgwInstallLabel">Zainstaluj aplikację</span></button></div><fieldset><legend id="pgwAccessLegend">Tryb dostępności</legend><label><input type="checkbox" id="pgwLarge"> <span id="pgwLargeLabel">Duży tekst</span></label><label><input type="checkbox" id="pgwContrast"> <span id="pgwContrastLabel">Wysoki kontrast</span></label><label><input type="checkbox" id="pgwMotion"> <span id="pgwMotionLabel">Mniej animacji</span></label></fieldset>`;
 const shade=document.createElement('div');shade.id='pgwPassportShade';shade.className='pgw-passport-shade no-i18n';document.body.append(drawer,shade);
 document.getElementById('pgwLanguage').onchange=e=>setLang(e.target.value);
 const open=()=>{drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');shade.classList.add('open');updateSuite();document.getElementById('pgwPassportClose')?.focus()};
 const close=()=>{drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');shade.classList.remove('open');document.getElementById('pgwPassportOpen')?.focus()};
 document.getElementById('pgwPassportOpen').onclick=open;document.getElementById('pgwPassportClose').onclick=close;shade.onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drawer.classList.contains('open'))close()});
 document.getElementById('pgwShare').onclick=()=>copy(shareUrl(),(SUITE[lang]||SUITE.pl).safeCopied);
 document.getElementById('pgwCopyCase').onclick=()=>copy(caseCode(),(SUITE[lang]||SUITE.pl).caseCopied);
 document.getElementById('pgwPrint').onclick=()=>window.print();document.getElementById('pgwEmail').onclick=openMail;document.getElementById('pgwClearContacts').onclick=clearContacts;
 for(const [id,cls] of [['pgwLarge','pgw-large'],['pgwContrast','pgw-contrast'],['pgwMotion','pgw-reduce-motion']])document.getElementById(id).onchange=e=>{document.documentElement.classList.toggle(cls,e.target.checked);saveAccess()};
 document.getElementById('pgwInstall').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;updateSuite()};
 loadAccess();renderSuiteLocale();updateNetwork();
}
function saveAccess(){localStorage.setItem(UI_KEY,JSON.stringify({large:document.documentElement.classList.contains('pgw-large'),contrast:document.documentElement.classList.contains('pgw-contrast'),motion:document.documentElement.classList.contains('pgw-reduce-motion')}))}
function loadAccess(){try{const a=JSON.parse(localStorage.getItem(UI_KEY)||'{}');document.documentElement.classList.toggle('pgw-large',!!a.large);document.documentElement.classList.toggle('pgw-contrast',!!a.contrast);document.documentElement.classList.toggle('pgw-reduce-motion',!!a.motion);for(const [id,v] of [['pgwLarge',a.large],['pgwContrast',a.contrast],['pgwMotion',a.motion]]){const e=document.getElementById(id);if(e)e.checked=!!v}}catch{}}
function updateNetwork(){const e=document.getElementById('pgwNet');if(!e)return;const l=SUITE[lang]||SUITE.pl;e.textContent=navigator.onLine?'● '+l.online:'● '+l.offline;e.className='pgw-net '+(navigator.onLine?'online':'offline')}
function updateSuite(){const p=safePayload(),count=(p.parts||[]).reduce((n,x)=>n+(Number(x[1])||1),0);const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('pgwCase',caseCode());set('pgwModel',p.deviceIndex||'—');set('pgwPartCount',String(count));const install=document.getElementById('pgwInstall');if(install)install.hidden=!installPrompt;renderSuiteLocale()}
const cssEscape=v=>globalThis.CSS?.escape?CSS.escape(String(v)):String(v).replace(/[^a-zA-Z0-9_-]/g,c=>'\\'+c.codePointAt(0).toString(16)+' ');
async function importShare(){let p=null;try{const m=location.hash.match(/(?:^#|&)pgw=([^&]+)/);if(m)p=b64d(m[1]);}catch{}const model=p?.deviceIndex||new URLSearchParams(location.search).get('model');if(!model)return;const wait=()=>new Promise(r=>setTimeout(r,350));for(let n=0;n<30;n++){if(document.getElementById('deviceSearch')&&document.querySelector('#deviceResults'))break;await wait()}const search=document.getElementById('deviceSearch');if(!search)return;search.value=model;search.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(r=>setTimeout(r,700));const norm=s=>String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'');const b=[...document.querySelectorAll('button[data-device]')].find(x=>norm(x.dataset.device)===norm(model));if(b)b.click();if(p?.parts?.length){await new Promise(r=>setTimeout(r,700));for(const [id,qty] of p.parts){const add=document.querySelector(`button[data-part="${cssEscape(id)}"]`);if(add)add.click();await wait();const input=document.querySelector(`input[data-qty="${cssEscape(id)}"]`);if(input){input.value=qty;input.dispatchEvent(new Event('change',{bubbles:true}))}}toast((SUITE[lang]||SUITE.pl).sharedLoaded)}}
function init(){const qp=new URLSearchParams(location.search).get('lang'),stored=localStorage.getItem(LANG_KEY),browser=navigator.language?.slice(0,2);lang=SUPPORTED.includes(qp)?qp:SUPPORTED.includes(stored)?stored:SUPPORTED.includes(browser)?browser:'pl';createSuite();const obs=new MutationObserver(queueTranslate);obs.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label']});window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;updateSuite()});window.addEventListener('storage',updateSuite);document.addEventListener('input',()=>setTimeout(updateSuite,50));document.addEventListener('change',()=>setTimeout(updateSuite,50));setInterval(updateSuite,1500);queueTranslate();importShare();const params=new URLSearchParams(location.search);if(params.get('focus')==='device')setTimeout(()=>document.getElementById('deviceSearch')?.focus(),500);if(params.get('passport')==='1')setTimeout(()=>document.getElementById('pgwPassportOpen')?.click(),500);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw-v050-v1.js').catch(()=>{});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
