window.PGW_CONFIG = {
  version: '20260710-v72-publish',
  appName: 'Formularz zapytania o części',
  recipientEmail: 'service@yato.pl',
  storageMode: 'drive',
  pdfOnly: true,
  showPrices: false,
  showStock: false,
  autosave: true,
  partRowLimit: 80,
  enableVatLookup: true,
  enableManualFallback: true,
  enableMappingTools: false,
  enableAdminPanel: true,
  adminPanelParam: 'admin',
  vatLookupProvider: 'mf-wl',
  postalCodesUrl: 'data/postal-codes.json',
  dataUrls: {
    devices: ['data/devices.json'],
    drawings: ['data/drawings.json'],
    parts: ['data/parts.json'],
    driveMap: ['data/drive-drawings-map.full.json', 'data/drive-drawings-map.converted.json', 'data/drive-drawings-map.json'],
    pdfDeviceOverrides: ['data/pdf-device-overrides.json'],
    pdfQualityReport: ['data/pdf-quality-report.json'],
    pdfOrphans: ['data/pdf-orphans.json'],
    pdfQaRules: ['data/pdf-qa-rules.json'],
    pdfOverrideCandidates: ['data/pdf-override-candidates.json'],
    deploymentState: ['data/deployment-state.json'],
    releaseInfo: ['data/release-info.json'],
    brandOverrides: ['data/brand-resolution-overrides.json'],
    pdfHeaderOverrides: ['data/pdf-header-overrides.json'],
    universalParts: ['data/universal-parts-zun.json'],
    universalPartLinks: ['data/universal-parts-zun-links.json'],
    partAssemblies: ['data/part-assemblies.json']
  }
};
