window.PGW_CONFIG = {
  supportedLanguages: ['pl','en'],
  defaultLanguage: 'pl',
  version: '20260714-v82-ui-i18n-foundation',
  appName: 'Formularz zapytania o części',
  recipientEmail: 'service@yato.pl',
  storageMode: 'drive',
  releaseChannel: 'stable-v82',
  cachePolicy: 'no-store',
  enableSmokeTestTools: true,
  pdfOnly: true,
  showPrices: false,
  showStock: false,
  autosave: true,
  partRowLimit: 80,
  enableVatLookup: true,
  enableManualFallback: true,
  enableMappingTools: false,
  enableAdminPanel: true,
  adminPanelParam: 'admin',
  vatLookupProvider: 'mf-wl',
  postalCodesUrl: 'data/postal-codes.json',
  dataUrls: {
    devices: ['data/devices.json'],
    drawings: ['data/drawings.json'],
    parts: ['data/parts.json'],
    driveMap: ['data/drive-drawings-map.full.json', 'data/drive-drawings-map.converted.json', 'data/drive-drawings-map.json'],
    pdfDeviceOverrides: ['data/pdf-device-overrides.json'],
    pdfQualityReport: ['data/pdf-quality-report.json'],
    pdfOrphans: ['data/pdf-orphans.json'],
    pdfQaRules: ['data/pdf-qa-rules.json'],
    pdfOverrideCandidates: ['data/pdf-override-candidates.json'],
      pdfDisplayPolicy: ['data/pdf-display-policy.json'],
      pdfStandardizationAudit: ['data/pdf-standardization-audit.json'],
      pdfRepairCandidates: ['data/pdf-repair-candidates.json'],
      pdfViewerFallbacks: ['data/pdf-viewer-fallbacks.json'],
      modelAliases: ['data/model-aliases.json'],
      pdfPublicationQuarantine: ['data/pdf-publication-quarantine.json'],
      pdfPublicationRepairPlan: ['data/pdf-publication-repair-plan.json'],
      pdfPublicationReadiness: ['data/pdf-publication-readiness.json'],
    deploymentState: ['data/deployment-state.json'],
    releaseInfo: ['data/release-info.json'],
    brandOverrides: ['data/brand-resolution-overrides.json'],
    pdfHeaderOverrides: ['data/pdf-header-overrides.json'],
    universalParts: ['data/universal-parts-zun.json'],
    universalPartLinks: ['data/universal-parts-zun-links.json'],
    partAssemblies: ['data/part-assemblies.json']
  }
};
